name: Reusable workflow example

on:
  workflow_call:

jobs:
  uuid:
    runs-on: ubuntu-latest
    outputs:
      uuid: ${{ steps.id.outputs.uuid }}
    steps:
      - name: Create uuid
        id: uuid
        run: | 
            echo "uuid=$(uuidgen)" >> $GITHUB_OUTPUT

  upload:
    runs-on: ubuntu-latest
    needs: uuid
    steps:
      - run: |
          echo "abc" > example.txt

      - name: Upload
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: "example.txt-${{ needs.uuid.outputs.uuid }}"
          path: "example.txt"
          if-no-files-found: error
          retention-days: 5

  download:
    runs-on: ubuntu-latest
    needs: [upload, uuid]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "example.txt-${{ needs.uuid.outputs.uuid }}"
          path: example.txt
      - run: |
          cat example.txt